######################################################################
# Automatically generated by qmake (1.07a) Fri Jan 14 12:47:45 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += map.h map_editor.h tileset.h
SOURCES += hoa_map_editor.cpp map.cpp map_editor.cpp tileset.cpp
