--------------------------------------------------------------------------------
-- 01_return_scene.lua
--
-- Similar to a01_opening_scene.lua and using the same map. The entire map is a
-- scene of soldiers marching through the desert back to their homes.
--------------------------------------------------------------------------------
local ns = {}
setmetatable(ns, {__index = _G})
a01_return_scene = ns;
setfenv(1, ns);

-- Set to true to turn on debugging messages generated by this map script
DEBUG = false; 

data_file = "lua/data/maps/harrvah_desert_cave_path.lua";
location_filename = "img/portraits/locations/blank.png";
map_name = "";

sound_filenames = {};

music_filenames = {};

enemy_ids = {};

-- Primary Map Classes
Map = {};
ObjectManager = {};
DialogueManager = {};
EventManager = {};
TreasureManager = {};
GlobalEvents = {};

-- Containers used to hold pointers to various class objects.
contexts = {};
zones = {};
objects = {};
sprites = {};
dialogues = {};
events = {};

-- All custom map functions are contained within the following table.
-- String keys in this table serves as the names of these functions. 
functions = {};

-- Shorthand names for map contexts
contexts["base"] = hoa_map.MapMode.CONTEXT_01; -- The only context for this map


function Load(m)
	Map = m;

	ObjectManager = Map.object_supervisor;
	DialogueManager = Map.dialogue_supervisor;
	EventManager = Map.event_supervisor;
	TreasureManager = Map.treasure_supervisor;
	GlobalEvents = Map.map_event_group;

	-- Setup the order in which we wish to draw the tile and object layers
	Map:ClearLayerOrder();
	Map:AddTileLayerToOrder(0);
	Map:AddTileLayerToOrder(1);
	Map:AddObjectLayerToOrder(0);
	Map:AddTileLayerToOrder(2);

	CreateSprites();
	CreateDialogues();
	CreateEvents();

	VideoManager:EnableLightOverlay(hoa_video.Color(0.0, 0.0, 0.3, 0.6));

	-- This entire map is played out in scene state. As soon as the map is loaded, we start the chain of events.
	Map:PushState(hoa_map.MapMode.STATE_SCENE);
	Map:DisableIntroductionVisuals();
	Map:ShowStaminaBar(false);
	Map:ShowDialogueIcons(false);
	Map:SetCamera(sprites["claudius"]);
	EventManager:StartEvent(event_chains["main_event"]);
	IfPrintDebug(DEBUG, "Map loading complete");
end



function Update()
	-- TODO: add a point light on left side of screen representing the city ablaze with gradually increasing intensity
end



function Draw()
	Map:DrawMapLayers();
end

--------------------------------------------------------------------------------
-- Setup functions
--------------------------------------------------------------------------------

-- Creates the sprites for all characters in the party
function CreateSprites()
	IfPrintDebug(DEBUG, "Creating sprites...");

	-- Global starting coordinates for the center of the group of knights. All sprites
	-- use these coordinates in determining their initial positions.
	local start_x = 300;
	local start_y = 24;

	sprites["claudius"] = ConstructSprite("Claudius", 1000, start_x + 0.5, start_y + 0.5);
	sprites["claudius"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["claudius"]:SetNoCollision(true);
	sprites["claudius"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["claudius"]);

	sprites["mark"] = ConstructSprite("Knight01", 1001, start_x + 1.5, start_y + 3);
	sprites["mark"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["mark"]:SetName(hoa_system.Translate("Mark"));
	sprites["mark"]:SetNoCollision(true);
	sprites["mark"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["mark"]);

	sprites["lukar"] = ConstructSprite("Knight01", 1002, start_x + 4, start_y);
	sprites["lukar"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["lukar"]:SetName(hoa_system.Translate("Lukar"));
	sprites["lukar"]:SetNoCollision(true);
	sprites["lukar"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["lukar"]);

	sprites["captain"] = ConstructSprite("Knight06", 2000, start_x + 8, start_y);
	sprites["captain"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["captain"]:SetName(hoa_system.Translate("Captain Bravis"));
	sprites["captain"]:SetNoCollision(true);
	sprites["captain"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["captain"]);

	sprites["sergeant"] = ConstructSprite("Knight05", 2001, start_x + 2.5, start_y - 2);
	sprites["sergeant"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["sergeant"]:SetName(hoa_system.Translate("Sergeant Methus"));
	sprites["sergeant"]:SetNoCollision(true);
	sprites["sergeant"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["sergeant"]);

	sprites["knight01"] = ConstructSprite("Knight04", 2002, start_x + 6, start_y - 3.5);
	sprites["knight01"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight01"]:SetNoCollision(true);
	sprites["knight01"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["knight01"]);

	sprites["knight02"] = ConstructSprite("Knight02", 2003, start_x + 6, start_y - 3.5);
	sprites["knight02"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight02"]:SetNoCollision(true);
	sprites["knight02"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();

	ObjectManager:AddObject(sprites["knight02"]);

	sprites["knight03"] = ConstructSprite("Knight03", 2004, start_x + 6.5, start_y + 2);
	sprites["knight03"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight03"]:SetNoCollision(true);
	sprites["knight03"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["knight03"]);

	sprites["knight04"] = ConstructSprite("Knight02", 2005, start_x - 3, start_y - 3);
	sprites["knight04"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight04"]:SetNoCollision(true);
	sprites["knight04"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["knight04"]);

	sprites["knight05"] = ConstructSprite("Knight01", 2006, start_x - 4, start_y + 5);
	sprites["knight05"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight05"]:SetNoCollision(true);
	sprites["knight05"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["knight05"]);

	sprites["knight06"] = ConstructSprite("Knight02", 2007, start_x - 5, start_y - 1);
	sprites["knight06"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight06"]:SetNoCollision(true);
	sprites["knight06"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["knight06"]);

	sprites["knight07"] = ConstructSprite("Knight03", 2008, start_x - 5, start_y - 5);
	sprites["knight07"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight07"]:SetNoCollision(true);
	sprites["knight07"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["knight07"]);

	sprites["knight08"] = ConstructSprite("Knight01", 2009, start_x - 6, start_y + 2);
	sprites["knight08"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight08"]:SetNoCollision(true);
	sprites["knight08"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["knight08"]);

	sprites["knight09"] = ConstructSprite("Knight03", 2010, start_x - 8, start_y - 4);
	sprites["knight09"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight09"]:SetNoCollision(true);
	sprites["knight09"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["knight09"]);

	sprites["knight10"] = ConstructSprite("Knight02", 2011, start_x - 9, start_y + 5);
	sprites["knight10"]:SetDirection(hoa_map.MapMode.WEST);
	sprites["knight10"]:SetNoCollision(true);
	sprites["knight10"]:GetAnimation(hoa_map.MapMode.ANIM_WALKING_WEST):RandomizeCurrentLoopProgress();
	ObjectManager:AddObject(sprites["knight10"]);
	
	-- This sprite is the scout that runs in from the left side of the screen
	sprites["knight_scout"] = ConstructSprite("Knight01", 2012, 20, start_y);
	sprites["knight_scout"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight_scout"]:SetNoCollision(true);
	ObjectManager:AddObject(sprites["knight_scout"]);
end


-- Creates all dialogue that takes place through characters and events
function CreateDialogues()
	IfPrintDebug(DEBUG, "Creating dialogues...");

	event_dialogues = {}; -- Holds IDs of the dialogues used during events
	local dialogue;
	local text;

	event_dialogues["march_start"] = 10;
	dialogue = hoa_map.MapDialogue.Create(event_dialogues["march_start"]);
		dialogue:SetInputBlocked(true);
		text = hoa_system.Translate("I can't wait to get back home. Maybe now that the water supply is restored they'll finally let us bathe again. I've been covered in sand for days.");
		dialogue:AddLine(text, sprites["mark"]:GetObjectID());
		dialogue:AddLineTiming(8000);

	event_dialogues["red_sky"] = 20;
	dialogue = hoa_map.MapDialogue.Create(event_dialogues["red_sky"]);
		dialogue:SetInputBlocked(true);
		text = hoa_system.Translate("That's odd, the sky is brighter in the direction of the city.");
		dialogue:AddLine(text, sprites["knight01"]:GetObjectID());
		dialogue:AddLineTiming(4000);
		text = hoa_system.Translate("I bet the citizens are out celebrating now that the water's returned. They're probably preparing to welcome us back as heroes!");
		dialogue:AddLine(text, sprites["mark"]:GetObjectID());
		dialogue:AddLineTiming(7000);
		text = hoa_system.Translate("Maybe...but who would still be awake at this hour?");
		dialogue:AddLine(text, sprites["sergeant"]:GetObjectID());
		dialogue:AddLineTiming(3000);
		text = hoa_system.Translate("Our scout should be returning soon, we'll find out then.");
		dialogue:AddLine(text, sprites["lukar"]:GetObjectID());
		dialogue:AddLineTiming(4000);

	event_dialogues["scout_report"] = 30;
	dialogue = hoa_map.MapDialogue.Create(event_dialogues["scout_report"]);
		text = hoa_system.Translate("Captain Bravis!");
		dialogue:AddLine(text, sprites["knight_scout"]:GetObjectID());
		dialogue:AddLineTiming(3000);
		text = hoa_system.Translate("Catch your breath soldier. What's wrong?");
		dialogue:AddLine(text, sprites["captain"]:GetObjectID());
		dialogue:AddLineTiming(4000);
		text = hoa_system.Translate("The city! *huff* The city...its ablaze!");
		dialogue:AddLine(text, sprites["knight_scout"]:GetObjectID());
		dialogue:AddLineTiming(3000);
		dialogue:AddLineEventAtEnd(310);
end


-- Creates all events and sets up the entire event sequence chain
function CreateEvents()
	IfPrintDebug(DEBUG, "Creating events...");

	event_chains = {};
	local event = {};

	-- Move all sprites away from the cave entrance
	local march_distance = -220;
	local total_march_distance = 280;

	event_chains["main_event"] = 10;
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"], sprites["claudius"], march_distance, 0);
	event:SetRelativeDestination(true);
	event:AddEventLinkAtStart(event_chains["main_event"] + 1);
	event:AddEventLinkAtStart(event_chains["main_event"] + 2);
	event:AddEventLinkAtStart(event_chains["main_event"] + 3);
	event:AddEventLinkAtStart(event_chains["main_event"] + 4);
	event:AddEventLinkAtStart(event_chains["main_event"] + 5);
	event:AddEventLinkAtStart(event_chains["main_event"] + 6);
	event:AddEventLinkAtStart(event_chains["main_event"] + 7);
	event:AddEventLinkAtStart(event_chains["main_event"] + 8);
	event:AddEventLinkAtStart(event_chains["main_event"] + 9);
	event:AddEventLinkAtStart(event_chains["main_event"] + 10);
	event:AddEventLinkAtStart(event_chains["main_event"] + 11);
	event:AddEventLinkAtStart(event_chains["main_event"] + 12);
	event:AddEventLinkAtStart(event_chains["main_event"] + 13);
	event:AddEventLinkAtStart(event_chains["main_event"] + 14);
	event:AddEventLinkAtStart(50, 4000);
	event:AddEventLinkAtStart(51, 20000);
	event:AddEventLinkAtEnd(25); -- The scout moves towards the main party as the dialogue ends
	event:AddEventLinkAtEnd(52, 2000); -- The scout makes his report
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 1, sprites["mark"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 2, sprites["sergeant"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 3, sprites["lukar"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 4, sprites["captain"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 5, sprites["knight01"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 6, sprites["knight02"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 7, sprites["knight03"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 8, sprites["knight04"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 9, sprites["knight05"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 10, sprites["knight06"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 11, sprites["knight07"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 12, sprites["knight08"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 13, sprites["knight09"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 14, sprites["knight10"], march_distance, 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(event_chains["main_event"] + 15, sprites["knight_scout"], total_march_distance + march_distance, 0);
	event:SetRelativeDestination(true);

	-- Create the dialogue
	event = hoa_map.DialogueEvent.Create(50, event_dialogues["march_start"]);
	event = hoa_map.DialogueEvent.Create(51, event_dialogues["red_sky"]);
	event = hoa_map.DialogueEvent.Create(52, event_dialogues["scout_report"]);

	-- Change movement speed of all sprites
	event = hoa_map.CustomEvent.Create(250, "ChangeSpriteMovementSpeed", "");

	-- Rush off to the city
	event = hoa_map.PathMoveSpriteEvent.Create(310, sprites["claudius"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event:AddEventLinkAtStart(250);
	event:AddEventLinkAtStart(311);
	event:AddEventLinkAtStart(312);
	event:AddEventLinkAtStart(313);
	event:AddEventLinkAtStart(314);
	event:AddEventLinkAtStart(315);
	event:AddEventLinkAtStart(316);
	event:AddEventLinkAtStart(317);
	event:AddEventLinkAtStart(318);
	event:AddEventLinkAtStart(319);
	event:AddEventLinkAtStart(320);
	event:AddEventLinkAtStart(321);
	event:AddEventLinkAtStart(322);
	event:AddEventLinkAtStart(323);
	event:AddEventLinkAtStart(324);
	event:AddEventLinkAtEnd(500);
	event = hoa_map.PathMoveSpriteEvent.Create(311, sprites["mark"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(312, sprites["lukar"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(313, sprites["captain"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(314, sprites["sergeant"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(315, sprites["knight01"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(316, sprites["knight02"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(317, sprites["knight03"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(318, sprites["knight04"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(319, sprites["knight05"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(320, sprites["knight06"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(321, sprites["knight07"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(322, sprites["knight08"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(323, sprites["knight09"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.PathMoveSpriteEvent.Create(324, sprites["knight10"], -(total_march_distance + march_distance), 0);
	event:SetRelativeDestination(true);
	event = hoa_map.MapTransitionEvent.Create(500, "lua/scripts/maps/a01_harrvah_capital_attack.lua");
end -- function CreateEvents()


-- Changes the speed of every sprite as they sprint toward the city
functions["ChangeSpriteMovementSpeed"] = function()
	sprites["claudius"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["mark"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["lukar"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["captain"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["sergeant"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight01"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight02"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight03"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight04"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight05"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight06"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight07"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight08"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight09"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
	sprites["knight10"]:SetMovementSpeed(hoa_map.MapMode.VERY_FAST_SPEED);
end

